Update loop to low level game event
QBCore-Remastered/qb-multicharacter pull request #8
Opened 2022-10-10 21:37 UTC by JericoFX

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

"CEventNetworkStartSession" will trigger when the player join the network session, so with this we dont need a constant while true to check if the player is online, i know the performance is almost null because the while true will stop after the player join.
The check for the resource start and for the Config.Debug is made becase the trigger ONLY get fired when the player join the server, so if you are testing something the NUI will never appear,

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

2022-10-10 22:26 UTC, Manason approved these changes

2022-10-10 22:26 UTC, Manason commented on client/main.lua
> +---@param args any - In the case of this event "CEventNetworkStartSession" doesnt trigger any
Where does this param come from? I don't see in function signature

2022-10-11 00:26 UTC, JericoFX commented on client/main.lua
> +---@param args any - In the case of this event "CEventNetworkStartSession" doesnt trigger any
I had to remove it because Lint was complaining but gameEventTriggered have a name and args, go to the link that i left in the comments

2022-10-11 03:00 UTC, Manason commented on client/main.lua
> +---@param args any - In the case of this event "CEventNetworkStartSession" doesnt trigger any
What was the lint error? I'm not sure how I feel about putting an argument in the function signature which isn't being captured.

2022-10-11 03:01 UTC, D4isDAVID commented on client/main.lua
> +---@param args any - In the case of this event "CEventNetworkStartSession" doesnt trigger any
The lint error probably was unused parameter.

2022-10-11 03:15 UTC, Manason commented on client/main.lua
> +---@param args any - In the case of this event "CEventNetworkStartSession" doesnt trigger any
Ah I see. I feel we should remove the unused parameter from the function header then.

2022-10-11 03:33 UTC, JericoFX commented on client/main.lua
> +---@param args any - In the case of this event "CEventNetworkStartSession" doesnt trigger any
Done

2022-10-11 04:08 UTC, D4isDAVID requested changes

2022-10-11 04:08 UTC, D4isDAVID commented on client/main.lua
> +    if name == "CEventNetworkStartSession" then
```suggestion
---This event is fired after low-level game events take place.
---https://docs.fivem.net/docs/scripting-reference/events/list/gameEventTriggered/
---@param name string  the game event name that was triggered
AddEventHandler("gameEventTriggered", function(name)
    if name == "CEventNetworkStartSession" then -- when a network session has started
```
The comment above `gameEventTriggered` should be relevant to itself, not `CEventNetworkStartSession`.

2022-10-11 04:08 UTC, D4isDAVID commented on config.lua
> +Config.Debug = false -- With the change of a while true over low game event, if you try to restart the script to test some stuff it wont work because the game event only get triggered when the player
This option should probably be renamed, at least in my opinion.
An option named `Debug` most of the time just enables debug messages, not anything else.
Perhaps it should be changed to `Config.SelectOnRestart`, or something similar.

2022-10-11 12:19 UTC, JericoFX commented on config.lua
> +Config.Debug = false -- With the change of a while true over low game event, if you try to restart the script to test some stuff it wont work because the game event only get triggered when the player
i think Debug with the comment is self explanatory, you guys can change it later

2022-10-11 12:23 UTC, JericoFX commented on client/main.lua
> +    if name == "CEventNetworkStartSession" then
in understand but that comment is just a copy and paste of the web page, need to be something else because doesn't explain much.

2022-10-11 15:25 UTC, TheiLLeniumStudios commented on config.lua
> +Config.Debug = false -- With the change of a while true over low game event, if you try to restart the script to test some stuff it wont work because the game event only get triggered when the player
Config.DebugMode seems to be better in this case

2022-10-11 17:04 UTC, D4isDAVID commented on client/main.lua
> +    if name == "CEventNetworkStartSession" then
This comment is indeed a copy paste of the web page, but it does not need to be anything else, it explains exactly what it needs

2022-10-11 21:57 UTC, closed without merging